---

- hosts: 'mysql'
  become: true
  become_user: root
  
  tasks:
  
  - name: Disabling Selinux
    selinux:
      policy: targeted
      state: permissive

  - name: Getting MariaDB Repos
    get_url:
      url: https://downloads.mariadb.com/MariaDB/mariadb_repo_setup
      dest: /tmp/mariadb_repo_setup
      
  - name: Activating MariaDB Repos
    shell: $(which bash) /tmp/mariadb_repo_setup --mariadb-server-version={{ mariadb_version }} --mariadb-maxscale-version={{ maxscale_version }}
        
  - name: Installing Additional Packages
    yum: 
      name={{ item }}
      state=present
    with_items:
      - epel-release
      - nano
      - MySQL-python

  - name: Upgrading All Yum Packages
    yum:
      name: '*'
      state: latest
      
  - name: Installing MariaDB Items
    yum:
      name={{ item }}
      state=present
    with_items:
      - MariaDB-server
      - MariaDB-client
       
  - name: Creating Server Config
    template:
      src: templates/server.j2
      dest: /etc/my.cnf.d/server.cnf
      owner: root
      group: root
      mode: 0644   

  - name: Creating MySQL log folder
    file:
      path: /var/log/mysql
      state: directory
      mode: 0755
      owner: mysql
      group: mysql

  - name: Starting MySQL
    service: 
      name: mysql
      state: restarted
  
  - name: Removing Anonymous MySQL Account
    mysql_user:
      name: ''
      host_all: yes
      state: absent

  - name: "Removing root@{{ ansible_nodename }}"
    mysql_user:
      name: root
      host: "{{ ansible_nodename }}"
      state: absent

  - name: "Removeing root@::1"
    mysql_user:
      name: root
      host: "::1"
      state: absent

  - name: Add DBA User
    mysql_user:
      name: "{{ dba_user }}"
      host: 'localhost'
      password: "{{ dba_pass }}"
      update_password: on_create
      priv: '*.*:ALL,GRANT'
      state: present  

  - name: Add DBA User
    mysql_user:
      name: "{{ dba_user }}"
      host: '127.0.0.1'
      password: "{{ dba_pass }}"
      update_password: on_create
      priv: '*.*:ALL,GRANT'
      state: present  

  - name: Add DBA User
    mysql_user:
      name: "{{ dba_user }}"
      host: '10.%'
      password: "{{ dba_pass }}"
      update_password: on_create
      priv: '*.*:ALL,GRANT'
      state: present
      
- hosts: 'node2,node3,node4'
  become: true
  become_user: root
  
  tasks:

  - name: Copying Backend Script
    copy: 
      src: sql/spider_backend.sql
      dest: /tmp
     
  - name: Creating Backend Tables          
    mysql_db:
      state: import
      name: all
      target: /tmp/spider_backend.sql
    ignore_errors: yes      
 
- hosts: 'node1'
  become: true
  become_user: root
  
  tasks:

  - name: Activating Spider Plugin
    mysql_db:
      state: import
      name: all
      target: /usr/share/mysql/install_spider.sql

  - name: Copying Spider Frontend Script
    copy: 
      src: sql/spider_frontend.sql
      dest: /tmp

  - name: Copying Mock Data To Server
    copy: 
      src: sql/mock_data.csv
      dest: /tmp   
      
  - name: Running Spider Frontend Script    
    mysql_db:
      state: import
      name: all
      target: /tmp/spider_frontend.sql
    ignore_errors: yes
            